use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use verificationforge_adapter_rust::RustAdapter;
use verificationforge_core::{CodeNode, CodeNodeKind, SymbolId, UniversalCodeGraph};
use verificationforge_runtime::{
    AdapterRegistry, CheckStatus, CheckpointGate, CheckpointGatePhase, ProcessExecutionAdapter,
    RepositorySnapshot, VerificationEngine,
};

fn temp_dir(name: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock before epoch")
        .as_nanos();
    std::env::temp_dir().join(format!("verificationforge-real-checkpoint-{name}-{nonce}"))
}

fn write_fixture(root: &Path, source: &str) {
    fs::create_dir_all(root.join("src")).expect("create source directory");
    fs::create_dir_all(root.join("tests")).expect("create integration directory");
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"checkpoint-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write manifest");
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"checkpoint-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write lockfile");
    fs::write(root.join("src/lib.rs"), source).expect("write source");
    fs::write(
        root.join("tests/integration.rs"),
        "use checkpoint_fixture::identity;\n\n#[test]\nfn integration_identity_path() {\n    assert_eq!(identity(23), 23);\n}\n",
    )
    .expect("write integration test");
}

fn graph() -> UniversalCodeGraph {
    let mut graph = UniversalCodeGraph::default();
    graph.add_node(CodeNode {
        id: SymbolId("rust:file:src/lib.rs".into()),
        kind: CodeNodeKind::File,
        language: Some("Rust".into()),
        path: Some("src/lib.rs".into()),
        display_name: "src/lib.rs".into(),
    });
    graph
}

fn engine() -> VerificationEngine {
    let mut registry = AdapterRegistry::default();
    registry.register(Arc::new(RustAdapter));
    VerificationEngine::new(registry, Arc::new(ProcessExecutionAdapter))
}

const BASELINE_SOURCE: &str = r#"pub fn identity(input: u8) -> u8 {
    input
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn property_identity() {
        for value in 0..=32 {
            assert_eq!(identity(value), value);
        }
    }
}
"#;

const CLEAN_CHECKPOINT_SOURCE: &str = r#"pub fn identity(input: u8) -> u8 {
    input
}

pub fn double(input: u8) -> u8 {
    input.saturating_mul(2)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn property_identity() {
        for value in 0..=32 {
            assert_eq!(identity(value), value);
        }
    }

    #[test]
    fn double_examples() {
        assert_eq!(double(4), 8);
    }
}
"#;

const NO_PROPERTY_MARKER_SOURCE: &str = r#"pub fn identity(input: u8) -> u8 {
    input
}

pub fn double(input: u8) -> u8 {
    input.saturating_mul(2)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn identity_examples() {
        for value in 0..=32 {
            assert_eq!(identity(value), value);
        }
    }

    #[test]
    fn double_examples() {
        assert_eq!(double(4), 8);
    }
}
"#;

#[test]
fn real_rust_checkpoint_accepts_affected_integration_property_security_and_dependencies() {
    let root = temp_dir("clean");
    write_fixture(&root, BASELINE_SOURCE);
    let baseline = RepositorySnapshot::capture(&root).expect("capture baseline");
    fs::write(root.join("src/lib.rs"), CLEAN_CHECKPOINT_SOURCE).expect("write checkpoint change");

    let report = CheckpointGate::verify(&engine(), &root, &baseline, &graph())
        .expect("real Rust Checkpoint gate should run");

    assert!(report.patch.accepted, "PatchGate prerequisite must pass");
    assert!(
        report.accepted,
        "clean affected checkpoint should be accepted"
    );
    assert!(!report.patch.impact.requires_full_verification);
    assert!(report.patch.impact.changed_paths.contains("src/lib.rs"));

    for phase in [
        CheckpointGatePhase::Integration,
        CheckpointGatePhase::Property,
        CheckpointGatePhase::Security,
        CheckpointGatePhase::Dependencies,
    ] {
        assert!(
            report.entries.iter().any(|entry| {
                entry.phase == phase
                    && entry.result.status == CheckStatus::Pass
                    && entry.result.has_reproducible_evidence()
            }),
            "required checkpoint phase {phase:?} must pass with evidence"
        );
    }

    for phase in [CheckpointGatePhase::Ui, CheckpointGatePhase::Api] {
        assert!(
            report.entries.iter().any(|entry| {
                entry.phase == phase && entry.result.status == CheckStatus::Skipped
            })
        );
    }

    fs::remove_dir_all(root).ok();
}

#[test]
fn real_rust_checkpoint_rejects_missing_property_verification_after_other_tests_pass() {
    let root = temp_dir("missing-property");
    write_fixture(&root, CLEAN_CHECKPOINT_SOURCE);
    let baseline = RepositorySnapshot::capture(&root).expect("capture baseline");
    fs::write(root.join("src/lib.rs"), NO_PROPERTY_MARKER_SOURCE)
        .expect("write checkpoint without property marker");

    let report = CheckpointGate::verify(&engine(), &root, &baseline, &graph())
        .expect("real Rust Checkpoint gate should run");

    assert!(
        report.patch.accepted,
        "ordinary PatchGate checks must still pass"
    );
    assert!(
        !report.accepted,
        "missing property proof must block checkpoint"
    );
    assert!(report.entries.iter().any(|entry| {
        entry.phase == CheckpointGatePhase::Integration
            && entry.result.status == CheckStatus::Pass
            && entry.result.has_reproducible_evidence()
    }));
    assert!(report.entries.iter().any(|entry| {
        entry.phase == CheckpointGatePhase::Property
            && entry.result.status == CheckStatus::Unsupported
    }));

    fs::remove_dir_all(root).ok();
}
