use std::fs;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::time::{SystemTime, UNIX_EPOCH};

use verificationforge_adapter_rust::RustAdapter;
use verificationforge_core::{CodeNode, CodeNodeKind, SymbolId, UniversalCodeGraph};
use verificationforge_runtime::{
    AdapterRegistry, CheckStatus, PatchGate, PatchGatePhase, ProcessExecutionAdapter,
    RepositorySnapshot, VerificationEngine,
};

fn temp_dir(name: &str) -> PathBuf {
    let nonce = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .expect("clock before epoch")
        .as_nanos();
    std::env::temp_dir().join(format!("verificationforge-real-patch-{name}-{nonce}"))
}

fn write_fixture(root: &Path, source: &str) {
    fs::create_dir_all(root.join("src")).expect("create source directory");
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"patch-fixture\"\nversion = \"0.1.0\"\nedition = \"2024\"\n",
    )
    .expect("write manifest");
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"patch-fixture\"\nversion = \"0.1.0\"\n",
    )
    .expect("write lockfile");
    fs::write(root.join("src/lib.rs"), source).expect("write source");
}

fn graph() -> UniversalCodeGraph {
    let mut graph = UniversalCodeGraph::default();
    graph.add_node(CodeNode {
        id: SymbolId("rust:file:src/lib.rs".into()),
        kind: CodeNodeKind::File,
        language: Some("Rust".into()),
        path: Some("src/lib.rs".into()),
        display_name: "src/lib.rs".into(),
    });
    graph
}

fn engine() -> VerificationEngine {
    let mut registry = AdapterRegistry::default();
    registry.register(Arc::new(RustAdapter));
    VerificationEngine::new(registry, Arc::new(ProcessExecutionAdapter))
}

const BASELINE_SOURCE: &str = r#"pub fn value() -> u8 {
    1
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn value_is_one() {
        assert_eq!(value(), 1);
    }
}
"#;

const CLEAN_PATCH_SOURCE: &str = r#"pub fn value() -> u8 {
    2
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn value_is_two() {
        assert_eq!(value(), 2);
    }
}
"#;

fn secret_patch_source() -> String {
    let field_name = ["api", "_key"].concat();
    let field_value = ["super-real-", "secret-12345"].concat();
    format!(
        "pub fn value() -> u8 {{\n    3\n}}\n\npub fn credential_value() -> usize {{\n    let {field_name} = \"{field_value}\";\n    {field_name}.len()\n}}\n\n#[cfg(test)]\nmod tests {{\n    use super::*;\n\n    #[test]\n    fn value_is_three() {{\n        assert_eq!(value(), 3);\n    }}\n}}\n"
    )
}

#[test]
fn real_rust_patch_gate_accepts_clean_impact_targeted_patch() {
    let root = temp_dir("clean");
    write_fixture(&root, BASELINE_SOURCE);
    let baseline = RepositorySnapshot::capture(&root).expect("capture baseline");
    fs::write(root.join("src/lib.rs"), CLEAN_PATCH_SOURCE).expect("write clean patch");

    let report = PatchGate::verify(&engine(), &root, &baseline, &graph())
        .expect("real Rust Patch gate should run");

    assert!(report.accepted, "clean real Rust patch should be accepted");
    assert!(!report.impact.requires_full_verification);
    assert_eq!(report.impact.changed_paths.len(), 1);
    assert!(report.impact.changed_paths.contains("src/lib.rs"));

    for phase in [
        PatchGatePhase::Parse,
        PatchGatePhase::Format,
        PatchGatePhase::Build,
        PatchGatePhase::Lint,
        PatchGatePhase::Secrets,
        PatchGatePhase::Placeholders,
        PatchGatePhase::Impact,
        PatchGatePhase::TargetedTests,
    ] {
        assert!(
            report.entries.iter().any(|entry| {
                entry.phase == phase
                    && entry.result.status == CheckStatus::Pass
                    && entry.result.has_reproducible_evidence()
            }),
            "required phase {phase:?} must pass with evidence"
        );
    }

    let targeted = report
        .entries
        .iter()
        .find(|entry| entry.phase == PatchGatePhase::TargetedTests)
        .expect("targeted test entry");
    assert!(
        targeted
            .result
            .findings
            .iter()
            .any(|finding| finding.message.contains("patch-fixture"))
    );

    fs::remove_dir_all(root).ok();
}

#[test]
fn real_rust_patch_gate_rejects_hardcoded_secret_even_when_code_builds() {
    let root = temp_dir("secret");
    write_fixture(&root, CLEAN_PATCH_SOURCE);
    let baseline = RepositorySnapshot::capture(&root).expect("capture baseline");
    let secret_patch = secret_patch_source();
    fs::write(root.join("src/lib.rs"), secret_patch).expect("write secret patch");

    let report = PatchGate::verify(&engine(), &root, &baseline, &graph())
        .expect("real Rust Patch gate should run");

    assert!(!report.accepted, "hardcoded secret must block the patch");
    assert!(report.entries.iter().any(|entry| {
        entry.phase == PatchGatePhase::Build && entry.result.status == CheckStatus::Pass
    }));
    assert!(report.entries.iter().any(|entry| {
        entry.phase == PatchGatePhase::TargetedTests && entry.result.status == CheckStatus::Pass
    }));
    assert!(report.entries.iter().any(|entry| {
        entry.phase == PatchGatePhase::Secrets
            && entry.result.status == CheckStatus::Fail
            && entry
                .result
                .findings
                .iter()
                .any(|finding| finding.code == "VF_HARDCODED_SECRET")
    }));

    fs::remove_dir_all(root).ok();
}
